apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app
  namespace: 2tier
  labels:
    app: app
spec:
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers: 
      - name: app
        image: kulbhushanmayer/nodejs-app:v1
        ports:
        - containerPort: 4000
          name: app
        envFrom:
        - configMapRef:
            name: db
        - secretRef:
            name: db-pwd
  replicas: 2
  selector:
    matchLabels:
      app: nodejs

## UPDATE 1 - Created ENV Variables using ConfigMap & Secret
# kubectl apply -f app.yml
# kubectl exec -it -n 2tier pod-name -- printenv
# kubectl logs -n 2tier pod-name

---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: 2tier
spec:
  type: ClusterIP
  ports:
  - name: app
    port: 80
    targetPort: app
    protocol: TCP
  selector:
    app: nodejs
