apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: 2tier
  labels:
    app: db
spec: 
  template:
    metadata:
      labels:
        app: pg
    spec: 
      containers: 
      - name: postgres
        image: postgres:13.4
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-pwd
              key: DB_PWD
          
  replicas: 1
  selector: # to create relation between ReplicaSet & POD
    matchLabels: # it will match the label avaiable in the POD Template under Line 11
      app: pg


# Apply; kubectl apply -f pg_deployment.yml
# Check resources got created: kubectl get all -n 2tier
# Check labels on resources: kubectl get all -n 2tier --show-labels
# Get details about resource: kubectl describe resource-type resource-name -n namespace-name
# Get the logs for a POD: kubectl logs pod-name -n 2tier

### update 1
# Create Secret: kubectl create secret generic db-pwd --from-literal=DB_PWD=india123 -n 2tier
# apply the file: kubectl apply -f pg_deployment.yml
# Check resources got created: kubectl get all -n 2tier
# POD Status should be Running